# Generated by Django 4.2.4 on 2023-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("release_date", models.DateField()),
                ("poster_path", models.CharField(max_length=255)),
                ("backdrop_path", models.CharField(max_length=255)),
                ("original_language", models.CharField(max_length=10)),
                ("original_title", models.CharField(max_length=255)),
                ("popularity", models.FloatField()),
                ("vote_average", models.FloatField()),
                ("vote_count", models.PositiveIntegerField()),
                ("adult", models.BooleanField()),
                ("video", models.BooleanField()),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True, related_name="acted_in", to="imdb_api.person"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        blank=True, related_name="directed", to="imdb_api.person"
                    ),
                ),
                ("genres", models.ManyToManyField(to="imdb_api.genre")),
            ],
        ),
    ]
