# Generated by Django 4.2.4 on 2023-09-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0005_alter_movie_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
