# Generated by Django 4.2.4 on 2023-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0006_alter_movie_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
