# Generated by Django 4.2.4 on 2023-09-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imdb_api", "0008_person_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.RemoveField(
            model_name="person",
            name="user",
        ),
    ]
