# Generated by Django 4.2.4 on 2023-09-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imdb_api", "0009_delete_customuser_remove_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(null=True),
        ),
    ]
